version: '3'

services:
  frontend:
    image: nginx:1.12-alpine
    volumes:
    - ./frontend:/usr/share/nginx/html
    ports:
    - 0.0.0.0:3000:80
    environment:
      - NGINX_PORT=80

  backend:
    build: ./backend
    ports:
    - 0.0.0.0:5000:5000
    restart: unless-stopped
